<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://ws.aramex.net/ShippingAPI/v1/" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" name="Service_1_0" targetNamespace="http://ws.aramex.net/ShippingAPI/v1/">
<wsp:Policy wsu:Id="BasicHttpBinding_Service_1_0_policy">
<wsp:ExactlyOne>
<wsp:All>
<sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
<wsp:Policy>
<sp:TransportToken>
<wsp:Policy>
<sp:HttpsToken RequireClientCertificate="false"/>
</wsp:Policy>
</sp:TransportToken>
<sp:AlgorithmSuite>
<wsp:Policy>
<sp:Basic256/>
</wsp:Policy>
</sp:AlgorithmSuite>
<sp:Layout>
<wsp:Policy>
<sp:Strict/>
</wsp:Policy>
</sp:Layout>
</wsp:Policy>
</sp:TransportBinding>
</wsp:All>
</wsp:ExactlyOne>
</wsp:Policy>
<wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ser="http://schemas.microsoft.com/2003/10/Serialization/" elementFormDefault="qualified" targetNamespace="http://ws.aramex.net/ShippingAPI/v1/">
<xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
<xs:element name="ShipmentCreationRequest">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q1="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ClientInfo" nillable="true" type="q1:ClientInfo"/>
<xs:element xmlns:q2="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q2:Transaction"/>
<xs:element xmlns:q3="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Shipments" nillable="true" type="q3:ArrayOfShipment"/>
<xs:element xmlns:q4="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="LabelInfo" nillable="true" type="q4:LabelInfo"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:complexType name="ClientInfo">
<xs:sequence>
<xs:element name="UserName" nillable="true" type="xs:string"/>
<xs:element name="Password" nillable="true" type="xs:string"/>
<xs:element name="Version" nillable="true" type="xs:string"/>
<xs:element name="AccountNumber" nillable="true" type="xs:string"/>
<xs:element name="AccountPin" nillable="true" type="xs:string"/>
<xs:element name="AccountEntity" nillable="true" type="xs:string"/>
<xs:element name="AccountCountryCode" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Source" type="xs:int"/>
<xs:element minOccurs="0" name="PreferredLanguageCode" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q5="http://ws.aramex.net/ShippingAPI/v1/" name="ClientInfo" nillable="true" type="q5:ClientInfo"/>
<xs:complexType name="Transaction">
<xs:sequence>
<xs:element name="Reference1" nillable="true" type="xs:string"/>
<xs:element name="Reference2" nillable="true" type="xs:string"/>
<xs:element name="Reference3" nillable="true" type="xs:string"/>
<xs:element name="Reference4" nillable="true" type="xs:string"/>
<xs:element name="Reference5" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q6="http://ws.aramex.net/ShippingAPI/v1/" name="Transaction" nillable="true" type="q6:Transaction"/>
<xs:complexType name="ArrayOfShipment">
<xs:sequence>
<xs:element xmlns:q7="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" maxOccurs="unbounded" name="Shipment" nillable="true" type="q7:Shipment"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q8="http://ws.aramex.net/ShippingAPI/v1/" name="ArrayOfShipment" nillable="true" type="q8:ArrayOfShipment"/>
<xs:complexType name="Shipment">
<xs:sequence>
<xs:element minOccurs="0" name="Reference1" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Reference2" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Reference3" nillable="true" type="xs:string"/>
<xs:element xmlns:q9="http://ws.aramex.net/ShippingAPI/v1/" name="Shipper" nillable="true" type="q9:Party"/>
<xs:element xmlns:q10="http://ws.aramex.net/ShippingAPI/v1/" name="Consignee" nillable="true" type="q10:Party"/>
<xs:element xmlns:q11="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ThirdParty" nillable="true" type="q11:Party"/>
<xs:element name="ShippingDateTime" type="xs:dateTime"/>
<xs:element minOccurs="0" name="DueDate" type="xs:dateTime"/>
<xs:element minOccurs="0" name="Comments" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="PickupLocation" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="OperationsInstructions" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="AccountingInstrcutions" nillable="true" type="xs:string"/>
<xs:element xmlns:q12="http://ws.aramex.net/ShippingAPI/v1/" name="Details" nillable="true" type="q12:ShipmentDetails"/>
<xs:element xmlns:q13="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Attachments" nillable="true" type="q13:ArrayOfAttachment"/>
<xs:element minOccurs="0" name="ForeignHAWB" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="TransportType_x0020_" type="xs:int"/>
<xs:element minOccurs="0" name="PickupGUID" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Number" nillable="true" type="xs:string"/>
<xs:element xmlns:q14="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ScheduledDelivery" nillable="true" type="q14:ScheduledDelivery"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q15="http://ws.aramex.net/ShippingAPI/v1/" name="Shipment" nillable="true" type="q15:Shipment"/>
<xs:complexType name="Party">
<xs:sequence>
<xs:element minOccurs="0" name="Reference1" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Reference2" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="AccountNumber" nillable="true" type="xs:string"/>
<xs:element xmlns:q16="http://ws.aramex.net/ShippingAPI/v1/" name="PartyAddress" nillable="true" type="q16:Address"/>
<xs:element xmlns:q17="http://ws.aramex.net/ShippingAPI/v1/" name="Contact" nillable="true" type="q17:Contact"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q18="http://ws.aramex.net/ShippingAPI/v1/" name="Party" nillable="true" type="q18:Party"/>
<xs:complexType name="Address">
<xs:sequence>
<xs:element name="Line1" nillable="true" type="xs:string"/>
<xs:element name="Line2" nillable="true" type="xs:string"/>
<xs:element name="Line3" nillable="true" type="xs:string"/>
<xs:element name="City" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="StateOrProvinceCode" nillable="true" type="xs:string"/>
<xs:element name="PostCode" nillable="true" type="xs:string"/>
<xs:element name="CountryCode" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Longitude" type="xs:decimal"/>
<xs:element minOccurs="0" name="Latitude" type="xs:decimal"/>
<xs:element minOccurs="0" name="BuildingNumber" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="BuildingName" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Floor" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Apartment" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="POBox" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Description" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q19="http://ws.aramex.net/ShippingAPI/v1/" name="Address" nillable="true" type="q19:Address"/>
<xs:complexType name="Contact">
<xs:sequence>
<xs:element minOccurs="0" name="Department" nillable="true" type="xs:string"/>
<xs:element name="PersonName" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Title" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="CompanyName" nillable="true" type="xs:string"/>
<xs:element name="PhoneNumber1" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="PhoneNumber1Ext" nillable="true" type="xs:string"/>
<xs:element name="PhoneNumber2" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="PhoneNumber2Ext" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="FaxNumber" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="CellPhone" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="EmailAddress" nillable="true" type="xs:string"/>
<xs:element name="Type" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q20="http://ws.aramex.net/ShippingAPI/v1/" name="Contact" nillable="true" type="q20:Contact"/>
<xs:complexType name="ShipmentDetails">
<xs:sequence>
<xs:element xmlns:q21="http://ws.aramex.net/ShippingAPI/v1/" name="Dimensions" nillable="true" type="q21:Dimensions"/>
<xs:element xmlns:q22="http://ws.aramex.net/ShippingAPI/v1/" name="ActualWeight" nillable="true" type="q22:Weight"/>
<xs:element xmlns:q23="http://ws.aramex.net/ShippingAPI/v1/" name="ChargeableWeight" nillable="true" type="q23:Weight"/>
<xs:element name="DescriptionOfGoods" nillable="true" type="xs:string"/>
<xs:element name="GoodsOriginCountry" nillable="true" type="xs:string"/>
<xs:element name="NumberOfPieces" type="xs:int"/>
<xs:element name="ProductGroup" nillable="true" type="xs:string"/>
<xs:element name="ProductType" nillable="true" type="xs:string"/>
<xs:element name="PaymentType" nillable="true" type="xs:string"/>
<xs:element name="PaymentOptions" nillable="true" type="xs:string"/>
<xs:element xmlns:q24="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="CustomsValueAmount" nillable="true" type="q24:Money"/>
<xs:element xmlns:q25="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="CashOnDeliveryAmount" nillable="true" type="q25:Money"/>
<xs:element xmlns:q26="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="InsuranceAmount" nillable="true" type="q26:Money"/>
<xs:element xmlns:q27="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="CashAdditionalAmount" nillable="true" type="q27:Money"/>
<xs:element minOccurs="0" name="CashAdditionalAmountDescription" nillable="true" type="xs:string"/>
<xs:element xmlns:q28="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="CollectAmount" nillable="true" type="q28:Money"/>
<xs:element minOccurs="0" name="Services" nillable="true" type="xs:string"/>
<xs:element xmlns:q29="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Items" nillable="true" type="q29:ArrayOfShipmentItem"/>
<xs:element xmlns:q30="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="DeliveryInstructions" nillable="true" type="q30:DeliveryInstructions"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q31="http://ws.aramex.net/ShippingAPI/v1/" name="ShipmentDetails" nillable="true" type="q31:ShipmentDetails"/>
<xs:complexType name="Dimensions">
<xs:sequence>
<xs:element name="Length" type="xs:double"/>
<xs:element name="Width" type="xs:double"/>
<xs:element name="Height" type="xs:double"/>
<xs:element name="Unit" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q32="http://ws.aramex.net/ShippingAPI/v1/" name="Dimensions" nillable="true" type="q32:Dimensions"/>
<xs:complexType name="Weight">
<xs:sequence>
<xs:element name="Unit" nillable="true" type="xs:string"/>
<xs:element name="Value" type="xs:double"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q33="http://ws.aramex.net/ShippingAPI/v1/" name="Weight" nillable="true" type="q33:Weight"/>
<xs:complexType name="Money">
<xs:sequence>
<xs:element name="CurrencyCode" nillable="true" type="xs:string"/>
<xs:element name="Value" type="xs:double"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q34="http://ws.aramex.net/ShippingAPI/v1/" name="Money" nillable="true" type="q34:Money"/>
<xs:complexType name="ArrayOfShipmentItem">
<xs:sequence>
<xs:element xmlns:q35="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" maxOccurs="unbounded" name="ShipmentItem" nillable="true" type="q35:ShipmentItem"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q36="http://ws.aramex.net/ShippingAPI/v1/" name="ArrayOfShipmentItem" nillable="true" type="q36:ArrayOfShipmentItem"/>
<xs:complexType name="ShipmentItem">
<xs:sequence>
<xs:element name="PackageType" nillable="true" type="xs:string"/>
<xs:element name="Quantity" type="xs:int"/>
<xs:element xmlns:q37="http://ws.aramex.net/ShippingAPI/v1/" name="Weight" nillable="true" type="q37:Weight"/>
<xs:element minOccurs="0" name="Comments" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Reference" nillable="true" type="xs:string"/>
<xs:element xmlns:q38="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="PiecesDimensions" nillable="true" type="q38:ArrayOfDimensions"/>
<xs:element minOccurs="0" name="CommodityCode" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="GoodsDescription" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="CountryOfOrigin" nillable="true" type="xs:string"/>
<xs:element xmlns:q39="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="CustomsValue" nillable="true" type="q39:Money"/>
<xs:element minOccurs="0" name="ContainerNumber" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q40="http://ws.aramex.net/ShippingAPI/v1/" name="ShipmentItem" nillable="true" type="q40:ShipmentItem"/>
<xs:complexType name="ArrayOfDimensions">
<xs:sequence>
<xs:element xmlns:q41="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" maxOccurs="unbounded" name="Dimensions" nillable="true" type="q41:Dimensions"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q42="http://ws.aramex.net/ShippingAPI/v1/" name="ArrayOfDimensions" nillable="true" type="q42:ArrayOfDimensions"/>
<xs:complexType name="DeliveryInstructions">
<xs:sequence>
<xs:element name="Option" nillable="true" type="xs:string"/>
<xs:element name="Reference" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q43="http://ws.aramex.net/ShippingAPI/v1/" name="DeliveryInstructions" nillable="true" type="q43:DeliveryInstructions"/>
<xs:complexType name="ArrayOfAttachment">
<xs:sequence>
<xs:element xmlns:q44="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" maxOccurs="unbounded" name="Attachment" nillable="true" type="q44:Attachment"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q45="http://ws.aramex.net/ShippingAPI/v1/" name="ArrayOfAttachment" nillable="true" type="q45:ArrayOfAttachment"/>
<xs:complexType name="Attachment">
<xs:sequence>
<xs:element name="FileName" nillable="true" type="xs:string"/>
<xs:element name="FileExtension" nillable="true" type="xs:string"/>
<xs:element name="FileContents" nillable="true" type="xs:base64Binary"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q46="http://ws.aramex.net/ShippingAPI/v1/" name="Attachment" nillable="true" type="q46:Attachment"/>
<xs:complexType name="ScheduledDelivery">
<xs:sequence>
<xs:element minOccurs="0" name="PreferredDeliveryDate" nillable="true" type="xs:dateTime"/>
<xs:element minOccurs="0" name="PreferredDeliveryTimeFrame_x0020_" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="PreferredDeliveryTime" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q47="http://ws.aramex.net/ShippingAPI/v1/" name="ScheduledDelivery" nillable="true" type="q47:ScheduledDelivery"/>
<xs:complexType name="LabelInfo">
<xs:sequence>
<xs:element name="ReportID" type="xs:int"/>
<xs:element name="ReportType" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q48="http://ws.aramex.net/ShippingAPI/v1/" name="LabelInfo" nillable="true" type="q48:LabelInfo"/>
<xs:element name="ShipmentCreationResponse">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q49="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q49:Transaction"/>
<xs:element xmlns:q50="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Notifications" nillable="true" type="q50:ArrayOfNotification"/>
<xs:element minOccurs="0" name="HasErrors" type="xs:boolean"/>
<xs:element xmlns:q51="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Shipments" nillable="true" type="q51:ArrayOfProcessedShipment"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:complexType name="ArrayOfNotification">
<xs:sequence>
<xs:element xmlns:q52="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" maxOccurs="unbounded" name="Notification" nillable="true" type="q52:Notification"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q53="http://ws.aramex.net/ShippingAPI/v1/" name="ArrayOfNotification" nillable="true" type="q53:ArrayOfNotification"/>
<xs:complexType name="Notification">
<xs:sequence>
<xs:element name="Code" nillable="true" type="xs:string"/>
<xs:element name="Message" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q54="http://ws.aramex.net/ShippingAPI/v1/" name="Notification" nillable="true" type="q54:Notification"/>
<xs:complexType name="ArrayOfProcessedShipment">
<xs:sequence>
<xs:element xmlns:q55="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" maxOccurs="unbounded" name="ProcessedShipment" nillable="true" type="q55:ProcessedShipment"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q56="http://ws.aramex.net/ShippingAPI/v1/" name="ArrayOfProcessedShipment" nillable="true" type="q56:ArrayOfProcessedShipment"/>
<xs:complexType name="ProcessedShipment">
<xs:sequence>
<xs:element name="ID" nillable="true" type="xs:string"/>
<xs:element name="Reference1" nillable="true" type="xs:string"/>
<xs:element name="Reference2" nillable="true" type="xs:string"/>
<xs:element name="Reference3" nillable="true" type="xs:string"/>
<xs:element name="ForeignHAWB" nillable="true" type="xs:string"/>
<xs:element name="HasErrors" type="xs:boolean"/>
<xs:element xmlns:q57="http://ws.aramex.net/ShippingAPI/v1/" name="Notifications" nillable="true" type="q57:ArrayOfNotification"/>
<xs:element xmlns:q58="http://ws.aramex.net/ShippingAPI/v1/" name="ShipmentLabel" nillable="true" type="q58:ShipmentLabel"/>
<xs:element xmlns:q59="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ShipmentDetails" nillable="true" type="q59:ProcessedShipmentDetails"/>
<xs:element xmlns:q60="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ShipmentAttachments" nillable="true" type="q60:ArrayOfProcessedShipmentAttachment"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q61="http://ws.aramex.net/ShippingAPI/v1/" name="ProcessedShipment" nillable="true" type="q61:ProcessedShipment"/>
<xs:complexType name="ShipmentLabel">
<xs:sequence>
<xs:element name="LabelURL" nillable="true" type="xs:string"/>
<xs:element name="LabelFileContents" nillable="true" type="xs:base64Binary"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q62="http://ws.aramex.net/ShippingAPI/v1/" name="ShipmentLabel" nillable="true" type="q62:ShipmentLabel"/>
<xs:complexType name="ProcessedShipmentDetails">
<xs:sequence>
<xs:element name="Origin" nillable="true" type="xs:string"/>
<xs:element name="Destination" nillable="true" type="xs:string"/>
<xs:element xmlns:q63="http://ws.aramex.net/ShippingAPI/v1/" name="ChargeableWeight" nillable="true" type="q63:Weight"/>
<xs:element name="DescriptionOfGoods" nillable="true" type="xs:string"/>
<xs:element name="GoodsOriginCountry" nillable="true" type="xs:string"/>
<xs:element name="NumberOfPieces" type="xs:int"/>
<xs:element name="ProductGroup" nillable="true" type="xs:string"/>
<xs:element name="ProductType" nillable="true" type="xs:string"/>
<xs:element name="PaymentType" nillable="true" type="xs:string"/>
<xs:element name="PaymentOptions" nillable="true" type="xs:string"/>
<xs:element xmlns:q64="http://ws.aramex.net/ShippingAPI/v1/" name="CustomsValueAmount" nillable="true" type="q64:Money"/>
<xs:element xmlns:q65="http://ws.aramex.net/ShippingAPI/v1/" name="CashOnDeliveryAmount" nillable="true" type="q65:Money"/>
<xs:element xmlns:q66="http://ws.aramex.net/ShippingAPI/v1/" name="InsuranceAmount" nillable="true" type="q66:Money"/>
<xs:element xmlns:q67="http://ws.aramex.net/ShippingAPI/v1/" name="CashAdditionalAmount" nillable="true" type="q67:Money"/>
<xs:element xmlns:q68="http://ws.aramex.net/ShippingAPI/v1/" name="CollectAmount" nillable="true" type="q68:Money"/>
<xs:element name="Services" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q69="http://ws.aramex.net/ShippingAPI/v1/" name="ProcessedShipmentDetails" nillable="true" type="q69:ProcessedShipmentDetails"/>
<xs:complexType name="ArrayOfProcessedShipmentAttachment">
<xs:sequence>
<xs:element xmlns:q70="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" maxOccurs="unbounded" name="ProcessedShipmentAttachment" nillable="true" type="q70:ProcessedShipmentAttachment"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q71="http://ws.aramex.net/ShippingAPI/v1/" name="ArrayOfProcessedShipmentAttachment" nillable="true" type="q71:ArrayOfProcessedShipmentAttachment"/>
<xs:complexType name="ProcessedShipmentAttachment">
<xs:sequence>
<xs:element name="Name" nillable="true" type="xs:string"/>
<xs:element xmlns:q72="http://ws.aramex.net/ShippingAPI/v1/" name="Type" type="q72:ProcessedShipmentAttachmentType"/>
<xs:element name="Url" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q73="http://ws.aramex.net/ShippingAPI/v1/" name="ProcessedShipmentAttachment" nillable="true" type="q73:ProcessedShipmentAttachment"/>
<xs:simpleType name="ProcessedShipmentAttachmentType">
<xs:restriction base="xs:string">
<xs:enumeration value="CommercialInvoice"/>
</xs:restriction>
</xs:simpleType>
<xs:element xmlns:q74="http://ws.aramex.net/ShippingAPI/v1/" name="ProcessedShipmentAttachmentType" nillable="true" type="q74:ProcessedShipmentAttachmentType"/>
<xs:element name="LabelPrintingRequest">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q75="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ClientInfo" nillable="true" type="q75:ClientInfo"/>
<xs:element xmlns:q76="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q76:Transaction"/>
<xs:element minOccurs="0" name="ShipmentNumber" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="ProductGroup" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="OriginEntity" nillable="true" type="xs:string"/>
<xs:element xmlns:q77="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="LabelInfo" nillable="true" type="q77:LabelInfo"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="LabelPrintingResponse">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q78="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q78:Transaction"/>
<xs:element xmlns:q79="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Notifications" nillable="true" type="q79:ArrayOfNotification"/>
<xs:element minOccurs="0" name="HasErrors" type="xs:boolean"/>
<xs:element minOccurs="0" name="ShipmentNumber" nillable="true" type="xs:string"/>
<xs:element xmlns:q80="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ShipmentLabel" nillable="true" type="q80:ShipmentLabel"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="PickupCreationRequest">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q81="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ClientInfo" nillable="true" type="q81:ClientInfo"/>
<xs:element xmlns:q82="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q82:Transaction"/>
<xs:element xmlns:q83="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Pickup" nillable="true" type="q83:Pickup"/>
<xs:element xmlns:q84="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="LabelInfo" nillable="true" type="q84:LabelInfo"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:complexType name="Pickup">
<xs:sequence>
<xs:element xmlns:q85="http://ws.aramex.net/ShippingAPI/v1/" name="PickupAddress" nillable="true" type="q85:Address"/>
<xs:element xmlns:q86="http://ws.aramex.net/ShippingAPI/v1/" name="PickupContact" nillable="true" type="q86:Contact"/>
<xs:element name="PickupLocation" nillable="true" type="xs:string"/>
<xs:element name="PickupDate" type="xs:dateTime"/>
<xs:element name="ReadyTime" type="xs:dateTime"/>
<xs:element name="LastPickupTime" type="xs:dateTime"/>
<xs:element name="ClosingTime" type="xs:dateTime"/>
<xs:element name="Comments" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Reference1" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Reference2" nillable="true" type="xs:string"/>
<xs:element name="Vehicle" nillable="true" type="xs:string"/>
<xs:element xmlns:q87="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Shipments" nillable="true" type="q87:ArrayOfShipment"/>
<xs:element xmlns:q88="http://ws.aramex.net/ShippingAPI/v1/" name="PickupItems" nillable="true" type="q88:ArrayOfPickupItemDetail"/>
<xs:element minOccurs="0" name="Status" nillable="true" type="xs:string"/>
<xs:element xmlns:q89="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ExistingShipments" nillable="true" type="q89:ArrayOfExistingShipment"/>
<xs:element minOccurs="0" name="Branch" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="RouteCode" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q90="http://ws.aramex.net/ShippingAPI/v1/" name="Pickup" nillable="true" type="q90:Pickup"/>
<xs:complexType name="ArrayOfPickupItemDetail">
<xs:sequence>
<xs:element xmlns:q91="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" maxOccurs="unbounded" name="PickupItemDetail" nillable="true" type="q91:PickupItemDetail"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q92="http://ws.aramex.net/ShippingAPI/v1/" name="ArrayOfPickupItemDetail" nillable="true" type="q92:ArrayOfPickupItemDetail"/>
<xs:complexType name="PickupItemDetail">
<xs:sequence>
<xs:element name="ProductGroup" nillable="true" type="xs:string"/>
<xs:element name="ProductType" nillable="true" type="xs:string"/>
<xs:element name="NumberOfShipments" type="xs:int"/>
<xs:element name="PackageType" nillable="true" type="xs:string"/>
<xs:element name="Payment" nillable="true" type="xs:string"/>
<xs:element xmlns:q93="http://ws.aramex.net/ShippingAPI/v1/" name="ShipmentWeight" nillable="true" type="q93:Weight"/>
<xs:element xmlns:q94="http://ws.aramex.net/ShippingAPI/v1/" name="ShipmentVolume" nillable="true" type="q94:Volume"/>
<xs:element name="NumberOfPieces" type="xs:int"/>
<xs:element xmlns:q95="http://ws.aramex.net/ShippingAPI/v1/" name="CashAmount" nillable="true" type="q95:Money"/>
<xs:element xmlns:q96="http://ws.aramex.net/ShippingAPI/v1/" name="ExtraCharges" nillable="true" type="q96:Money"/>
<xs:element xmlns:q97="http://ws.aramex.net/ShippingAPI/v1/" name="ShipmentDimensions" nillable="true" type="q97:Dimensions"/>
<xs:element name="Comments" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q98="http://ws.aramex.net/ShippingAPI/v1/" name="PickupItemDetail" nillable="true" type="q98:PickupItemDetail"/>
<xs:complexType name="Volume">
<xs:sequence>
<xs:element name="Unit" nillable="true" type="xs:string"/>
<xs:element name="Value" type="xs:double"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q99="http://ws.aramex.net/ShippingAPI/v1/" name="Volume" nillable="true" type="q99:Volume"/>
<xs:complexType name="ArrayOfExistingShipment">
<xs:sequence>
<xs:element xmlns:q100="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" maxOccurs="unbounded" name="ExistingShipment" nillable="true" type="q100:ExistingShipment"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q101="http://ws.aramex.net/ShippingAPI/v1/" name="ArrayOfExistingShipment" nillable="true" type="q101:ArrayOfExistingShipment"/>
<xs:complexType name="ExistingShipment">
<xs:sequence>
<xs:element name="Number" nillable="true" type="xs:string"/>
<xs:element name="OriginEntity" nillable="true" type="xs:string"/>
<xs:element name="ProductGroup" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q102="http://ws.aramex.net/ShippingAPI/v1/" name="ExistingShipment" nillable="true" type="q102:ExistingShipment"/>
<xs:element name="PickupCreationResponse">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q103="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q103:Transaction"/>
<xs:element xmlns:q104="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Notifications" nillable="true" type="q104:ArrayOfNotification"/>
<xs:element minOccurs="0" name="HasErrors" type="xs:boolean"/>
<xs:element xmlns:q105="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ProcessedPickup" nillable="true" type="q105:ProcessedPickup"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:complexType name="ProcessedPickup">
<xs:sequence>
<xs:element name="ID" nillable="true" type="xs:string"/>
<xs:element name="GUID" type="ser:guid"/>
<xs:element name="Reference1" nillable="true" type="xs:string"/>
<xs:element name="Reference2" nillable="true" type="xs:string"/>
<xs:element xmlns:q106="http://ws.aramex.net/ShippingAPI/v1/" name="ProcessedShipments" nillable="true" type="q106:ArrayOfProcessedShipment"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q107="http://ws.aramex.net/ShippingAPI/v1/" name="ProcessedPickup" nillable="true" type="q107:ProcessedPickup"/>
<xs:element name="PickupCancelationRequest">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q108="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ClientInfo" nillable="true" type="q108:ClientInfo"/>
<xs:element xmlns:q109="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q109:Transaction"/>
<xs:element minOccurs="0" name="PickupGUID" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Comments" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="PickupCancelationResponse">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q110="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q110:Transaction"/>
<xs:element xmlns:q111="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Notifications" nillable="true" type="q111:ArrayOfNotification"/>
<xs:element minOccurs="0" name="HasErrors" type="xs:boolean"/>
<xs:element minOccurs="0" name="Message" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="ReserveRangeRequest">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q112="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ClientInfo" nillable="true" type="q112:ClientInfo"/>
<xs:element xmlns:q113="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q113:Transaction"/>
<xs:element minOccurs="0" name="Entity" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="ProductGroup" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Count" type="xs:int"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="ReserveRangeResponse">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q114="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q114:Transaction"/>
<xs:element xmlns:q115="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Notifications" nillable="true" type="q115:ArrayOfNotification"/>
<xs:element minOccurs="0" name="HasErrors" type="xs:boolean"/>
<xs:element minOccurs="0" name="FromWaybill" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="ToWaybill" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="LastReservedShipmentNumberRangeRequest">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q116="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ClientInfo" nillable="true" type="q116:ClientInfo"/>
<xs:element xmlns:q117="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q117:Transaction"/>
<xs:element minOccurs="0" name="Entity" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="ProductGroup" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="LastReservedShipmentNumberRangeResponse">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q118="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q118:Transaction"/>
<xs:element xmlns:q119="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Notifications" nillable="true" type="q119:ArrayOfNotification"/>
<xs:element minOccurs="0" name="HasErrors" type="xs:boolean"/>
<xs:element minOccurs="0" name="FromWaybill" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="ToWaybill" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="ScheduledDeliveryRequest">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q120="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ClientInfo" nillable="true" type="q120:ClientInfo"/>
<xs:element xmlns:q121="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q121:Transaction"/>
<xs:element xmlns:q122="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Address" nillable="true" type="q122:Address"/>
<xs:element xmlns:q123="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ScheduledDelivery" nillable="true" type="q123:ScheduledDelivery"/>
<xs:element minOccurs="0" name="ShipmentNumber" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="ProductGroup" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Entity" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="ConsigneePhone" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="ShipperNumber" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="ShipperReference" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Reference1" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Reference2" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="Reference3" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="ScheduledDeliveryResponse">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q124="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q124:Transaction"/>
<xs:element xmlns:q125="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Notifications" nillable="true" type="q125:ArrayOfNotification"/>
<xs:element minOccurs="0" name="HasErrors" type="xs:boolean"/>
<xs:element minOccurs="0" name="Id" type="xs:int"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="HoldCreationRequest">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q126="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ClientInfo" nillable="true" type="q126:ClientInfo"/>
<xs:element xmlns:q127="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q127:Transaction"/>
<xs:element xmlns:q128="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ShipmentHolds" nillable="true" type="q128:ArrayOfShipmentHoldDetails"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:complexType name="ArrayOfShipmentHoldDetails">
<xs:sequence>
<xs:element xmlns:q129="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" maxOccurs="unbounded" name="ShipmentHoldDetails" nillable="true" type="q129:ShipmentHoldDetails"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q130="http://ws.aramex.net/ShippingAPI/v1/" name="ArrayOfShipmentHoldDetails" nillable="true" type="q130:ArrayOfShipmentHoldDetails"/>
<xs:complexType name="ShipmentHoldDetails">
<xs:sequence>
<xs:element name="ShipmentNumber" nillable="true" type="xs:string"/>
<xs:element name="Comment" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q131="http://ws.aramex.net/ShippingAPI/v1/" name="ShipmentHoldDetails" nillable="true" type="q131:ShipmentHoldDetails"/>
<xs:element name="HoldCreationResponse">
<xs:complexType>
<xs:sequence>
<xs:element xmlns:q132="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Transaction" nillable="true" type="q132:Transaction"/>
<xs:element xmlns:q133="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="Notifications" nillable="true" type="q133:ArrayOfNotification"/>
<xs:element minOccurs="0" name="HasErrors" type="xs:boolean"/>
<xs:element xmlns:q134="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" name="ProcessedShipmentHolds" nillable="true" type="q134:ArrayOfProcessedShipmentHold"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:complexType name="ArrayOfProcessedShipmentHold">
<xs:sequence>
<xs:element xmlns:q135="http://ws.aramex.net/ShippingAPI/v1/" minOccurs="0" maxOccurs="unbounded" name="ProcessedShipmentHold" nillable="true" type="q135:ProcessedShipmentHold"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q136="http://ws.aramex.net/ShippingAPI/v1/" name="ArrayOfProcessedShipmentHold" nillable="true" type="q136:ArrayOfProcessedShipmentHold"/>
<xs:complexType name="ProcessedShipmentHold">
<xs:sequence>
<xs:element name="ID" nillable="true" type="xs:string"/>
<xs:element name="HasErrors" type="xs:boolean"/>
<xs:element xmlns:q137="http://ws.aramex.net/ShippingAPI/v1/" name="Notifications" nillable="true" type="q137:ArrayOfNotification"/>
</xs:sequence>
</xs:complexType>
<xs:element xmlns:q138="http://ws.aramex.net/ShippingAPI/v1/" name="ProcessedShipmentHold" nillable="true" type="q138:ProcessedShipmentHold"/>
</xs:schema>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/">
<xs:element name="anyType" nillable="true" type="xs:anyType"/>
<xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
<xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
<xs:element name="boolean" nillable="true" type="xs:boolean"/>
<xs:element name="byte" nillable="true" type="xs:byte"/>
<xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
<xs:element name="decimal" nillable="true" type="xs:decimal"/>
<xs:element name="double" nillable="true" type="xs:double"/>
<xs:element name="float" nillable="true" type="xs:float"/>
<xs:element name="int" nillable="true" type="xs:int"/>
<xs:element name="long" nillable="true" type="xs:long"/>
<xs:element name="QName" nillable="true" type="xs:QName"/>
<xs:element name="short" nillable="true" type="xs:short"/>
<xs:element name="string" nillable="true" type="xs:string"/>
<xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
<xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
<xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
<xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
<xs:element name="char" nillable="true" type="tns:char"/>
<xs:simpleType name="char">
<xs:restriction base="xs:int"/>
</xs:simpleType>
<xs:element name="duration" nillable="true" type="tns:duration"/>
<xs:simpleType name="duration">
<xs:restriction base="xs:duration">
<xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
<xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
<xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
</xs:restriction>
</xs:simpleType>
<xs:element name="guid" nillable="true" type="tns:guid"/>
<xs:simpleType name="guid">
<xs:restriction base="xs:string">
<xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
</xs:restriction>
</xs:simpleType>
<xs:attribute name="FactoryType" type="xs:QName"/>
<xs:attribute name="Id" type="xs:ID"/>
<xs:attribute name="Ref" type="xs:IDREF"/>
</xs:schema>
</wsdl:types>
<wsdl:message name="ShipmentCreationRequest">
<wsdl:part name="parameters" element="tns:ShipmentCreationRequest"/>
</wsdl:message>
<wsdl:message name="ShipmentCreationResponse">
<wsdl:part name="parameters" element="tns:ShipmentCreationResponse"/>
</wsdl:message>
<wsdl:message name="LabelPrintingRequest">
<wsdl:part name="parameters" element="tns:LabelPrintingRequest"/>
</wsdl:message>
<wsdl:message name="LabelPrintingResponse">
<wsdl:part name="parameters" element="tns:LabelPrintingResponse"/>
</wsdl:message>
<wsdl:message name="PickupCreationRequest">
<wsdl:part name="parameters" element="tns:PickupCreationRequest"/>
</wsdl:message>
<wsdl:message name="PickupCreationResponse">
<wsdl:part name="parameters" element="tns:PickupCreationResponse"/>
</wsdl:message>
<wsdl:message name="PickupCancelationRequest">
<wsdl:part name="parameters" element="tns:PickupCancelationRequest"/>
</wsdl:message>
<wsdl:message name="PickupCancelationResponse">
<wsdl:part name="parameters" element="tns:PickupCancelationResponse"/>
</wsdl:message>
<wsdl:message name="ReserveRangeRequest">
<wsdl:part name="parameters" element="tns:ReserveRangeRequest"/>
</wsdl:message>
<wsdl:message name="ReserveRangeResponse">
<wsdl:part name="parameters" element="tns:ReserveRangeResponse"/>
</wsdl:message>
<wsdl:message name="LastReservedShipmentNumberRangeRequest">
<wsdl:part name="parameters" element="tns:LastReservedShipmentNumberRangeRequest"/>
</wsdl:message>
<wsdl:message name="LastReservedShipmentNumberRangeResponse">
<wsdl:part name="parameters" element="tns:LastReservedShipmentNumberRangeResponse"/>
</wsdl:message>
<wsdl:message name="ScheduledDeliveryRequest">
<wsdl:part name="parameters" element="tns:ScheduledDeliveryRequest"/>
</wsdl:message>
<wsdl:message name="ScheduledDeliveryResponse">
<wsdl:part name="parameters" element="tns:ScheduledDeliveryResponse"/>
</wsdl:message>
<wsdl:message name="HoldCreationRequest">
<wsdl:part name="parameters" element="tns:HoldCreationRequest"/>
</wsdl:message>
<wsdl:message name="HoldCreationResponse">
<wsdl:part name="parameters" element="tns:HoldCreationResponse"/>
</wsdl:message>
<wsdl:portType name="Service_1_0">
<wsdl:operation name="CreateShipments">
<wsdl:input wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CreateShipments" name="ShipmentCreationRequest" message="tns:ShipmentCreationRequest"/>
<wsdl:output wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CreateShipmentsResponse" name="ShipmentCreationResponse" message="tns:ShipmentCreationResponse"/>
</wsdl:operation>
<wsdl:operation name="PrintLabel">
<wsdl:input wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/PrintLabel" name="LabelPrintingRequest" message="tns:LabelPrintingRequest"/>
<wsdl:output wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/PrintLabelResponse" name="LabelPrintingResponse" message="tns:LabelPrintingResponse"/>
</wsdl:operation>
<wsdl:operation name="CreatePickup">
<wsdl:input wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CreatePickup" name="PickupCreationRequest" message="tns:PickupCreationRequest"/>
<wsdl:output wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CreatePickupResponse" name="PickupCreationResponse" message="tns:PickupCreationResponse"/>
</wsdl:operation>
<wsdl:operation name="CancelPickup">
<wsdl:input wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CancelPickup" name="PickupCancelationRequest" message="tns:PickupCancelationRequest"/>
<wsdl:output wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CancelPickupResponse" name="PickupCancelationResponse" message="tns:PickupCancelationResponse"/>
</wsdl:operation>
<wsdl:operation name="ReserveShipmentNumberRange">
<wsdl:input wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ReserveShipmentNumberRange" name="ReserveRangeRequest" message="tns:ReserveRangeRequest"/>
<wsdl:output wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ReserveShipmentNumberRangeResponse" name="ReserveRangeResponse" message="tns:ReserveRangeResponse"/>
</wsdl:operation>
<wsdl:operation name="GetLastShipmentsNumbersRange">
<wsdl:input wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/GetLastShipmentsNumbersRange" name="LastReservedShipmentNumberRangeRequest" message="tns:LastReservedShipmentNumberRangeRequest"/>
<wsdl:output wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/GetLastShipmentsNumbersRangeResponse" name="LastReservedShipmentNumberRangeResponse" message="tns:LastReservedShipmentNumberRangeResponse"/>
</wsdl:operation>
<wsdl:operation name="ScheduleDelivery">
<wsdl:input wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ScheduleDelivery" name="ScheduledDeliveryRequest" message="tns:ScheduledDeliveryRequest"/>
<wsdl:output wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ScheduleDeliveryResponse" name="ScheduledDeliveryResponse" message="tns:ScheduledDeliveryResponse"/>
</wsdl:operation>
<wsdl:operation name="HoldShipments">
<wsdl:input wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/HoldShipments" name="HoldCreationRequest" message="tns:HoldCreationRequest"/>
<wsdl:output wsaw:Action="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/HoldShipmentsResponse" name="HoldCreationResponse" message="tns:HoldCreationResponse"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="BasicHttpBinding_Service_1_0" type="tns:Service_1_0">
<wsp:PolicyReference URI="#BasicHttpBinding_Service_1_0_policy"/>
<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="CreateShipments">
<soap:operation soapAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CreateShipments" style="document"/>
<wsdl:input name="ShipmentCreationRequest">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="ShipmentCreationResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="PrintLabel">
<soap:operation soapAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/PrintLabel" style="document"/>
<wsdl:input name="LabelPrintingRequest">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="LabelPrintingResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="CreatePickup">
<soap:operation soapAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CreatePickup" style="document"/>
<wsdl:input name="PickupCreationRequest">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="PickupCreationResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="CancelPickup">
<soap:operation soapAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/CancelPickup" style="document"/>
<wsdl:input name="PickupCancelationRequest">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="PickupCancelationResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="ReserveShipmentNumberRange">
<soap:operation soapAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ReserveShipmentNumberRange" style="document"/>
<wsdl:input name="ReserveRangeRequest">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="ReserveRangeResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="GetLastShipmentsNumbersRange">
<soap:operation soapAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/GetLastShipmentsNumbersRange" style="document"/>
<wsdl:input name="LastReservedShipmentNumberRangeRequest">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="LastReservedShipmentNumberRangeResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="ScheduleDelivery">
<soap:operation soapAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/ScheduleDelivery" style="document"/>
<wsdl:input name="ScheduledDeliveryRequest">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="ScheduledDeliveryResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="HoldShipments">
<soap:operation soapAction="http://ws.aramex.net/ShippingAPI/v1/Service_1_0/HoldShipments" style="document"/>
<wsdl:input name="HoldCreationRequest">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="HoldCreationResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="Service_1_0">
<wsdl:port name="BasicHttpBinding_Service_1_0" binding="tns:BasicHttpBinding_Service_1_0">
<soap:address location="https://ws.dev.aramex.net/ShippingAPI.V2/Shipping/Service_1_0.svc"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>