{
    'name': 'Flex Stock',
    'version': '14.0.1.1.0',
    'summary': '',
    'description': '',
    'category': '',
    'author': 'Sohaib Alamleh||Flex-ops',
    'website': '',
    'license': '',
    'depends': ['base','stock'],
    'data': ['report/stock.xml'],
    'demo': [''],
    'installable': True,
    'auto_install': False,
}